### PR TITLE
Make sclack installable from pip in a more universal fashion

### PR DESCRIPTION
**Pull request by pprkut**
This is pull request #115, rebased and cleaned up.

### CODE REVIEW

**Comment by duynguyenhoang** [comment]
Could you please also fix the unit test, mentioned in https://github.com/haskellcamargo/sclack/pull/115#issuecomment-485754969

**Comment by pprkut** [comment]
@duynguyenhoang That's already in there :)

**Comment by SanketDG** [comment]
Pinging this again so that this can be merged

**Comment by duynguyenhoang** [comment]
Thank you @pprkut and @SanketDG

**Pull request merged**
